{
  "file_data": [
    {
      "desc": {
        "cause": "Under Investigation",
        "cluster": false,
        "cust_a": {
          "masked": true,
          "val": 4
        },
        "etr": "2020-12-17T14:00:00-0400",
        "start": "2020-12-17T09:18:27-0400"
      },
      "geom": {
        "a": [
          "se|qGrohfK_Zl~@gC_Yf^md@"
        ],
        "p": [
          "_y|qGfqifK"
        ]
      },
      "id": "3",
      "title": "Outage Information"
    }
  ],
  "file_title": "030322"
}
