{
  "file_data": [
    {
      "desc": {
        "cause": "Under Investigation",
        "cluster": false,
        "cust_a": {
          "val": 26
        },
        "etr": "2020-12-14T02:45:00-0400",
        "start": "2020-12-13T22:43:15-0400"
      },
      "geom": {
        "a": [
          "azvmGvtuhKkAfEgLC}Hi@yFiC`RwKnCtBxHpG"
        ],
        "p": [
          "iiwmGtsuhK"
        ]
      },
      "id": "1",
      "title": "Outage Information"
    }
  ],
  "file_title": "030322"
}
